ShoeStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView

app_name = 'core'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
]

product/urls.py
from django.urls import path
from .views import ProductDetailView, CategoryView

app_name = 'product'

urlpatterns = [
    path('<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('category/<slug:slug>/', CategoryView, name='category'),
]

user/urls.py
from django.urls import path
from .views import RegisterView, LoginView

app_name = 'user'

urlpatterns = [
    path('register/', RegisterView, name='register'),
    path('login/', LoginView, name='login'),
]

templates/homepage/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'homepage/img/fav.png' %}">
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>{% block title %}{% endblock %}</title>
	<!--
		CSS
		============================================= -->
	{% block sitecss %}
	{% endblock %}

	{% block extracss %}
	{% endblock %}

	{% block extrajs %}
	{% endblock %}
</head>

<body>

	<!-- Start Header Area -->
	{% include 'homepage/header.html' %}	
	<!-- End Header Area -->

	<!-- start banner Area -->
	{% block banner-area %}
	{% endblock banner-area %}
	<!-- End banner Area -->

	<!-- start features Area -->
	{% block features-area %}
	{% endblock features-area %}
	<!-- end features Area -->

	<!-- Start category Area -->
	{% block category-area %}
	{% endblock category-area %}
	<!-- End category Area -->

	<!-- start product Area -->
	{% block product-area %}
		{% block product %}
		{% endblock product %}
	{% endblock product-area %}
	<!-- end product Area -->
	
	<!-- Start exclusive deal Area -->
	{% block exclusive-deal %}
	{% endblock exclusive-deal %}
	<!-- End exclusive deal Area -->

	<!-- Start brand Area -->
	{% block brand-section_gap %}
	{% endblock brand-section_gap %}
	<!-- End brand Area -->

	<!-- Start related-product Area -->
	{% block related-product %}	
	{% endblock related-product %}
	<!-- End related-product Area -->

	<!-- start footer Area -->
	{% include 'homepage/footer.html' %}
	<!-- End footer Area -->
	{% block sitejs %}
	{% endblock %}
</body>

</html>

templates/homepage/brand-section_gap.html
{% load staticfiles %}
<section class="brand-area section_gap">
    <div class="container">
        <div class="row">
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'homepage/img/brand/1.png' %}" alt="">
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'homepage/img/brand/2.png' %}" alt="">
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'homepage/img/brand/3.png' %}" alt="">
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'homepage/img/brand/4.png' %}" alt="">
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{% static 'homepage/img/brand/5.png' %}" alt="">
            </a>
        </div>
    </div>
</section>

templates/homepage/category.html
{% load staticfiles %}
<section class="category-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{% static 'homepage/img/category/c1.jpg' %}" alt="">
                            <a href="{% static 'homepage/img/category/c1.jpg' %}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{% static 'homepage/img/category/c2.jpg' %}" alt="">
                            <a href="{% static 'homepage/img/category/c2.jpg' %}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{% static 'homepage/img/category/c3.jpg' %}" alt="">
                            <a href="{% static 'homepage/img/category/c3.jpg' %}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Product for Couple</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{% static 'homepage/img/category/c4.jpg' %}" alt="">
                            <a href="{% static 'homepage/img/category/c4.jpg' %}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single-deal">
                    <div class="overlay"></div>
                    <img class="img-fluid w-100" src="{% static 'homepage/img/category/c5.jpg' %}" alt="">
                    <a href="{% static 'homepage/img/category/c5.jpg' %}" class="img-pop-up" target="_blank">
                        <div class="deal-details">
                            <h6 class="deal-title">Sneaker for Sports</h6>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

templates/homepage/exclusive-deal.html
{% load staticfiles %}
<section class="exclusive-deal-area">
    <div class="container-fluid">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-6 no-padding exclusive-left">
                <div class="row clock_sec clockdiv" id="clockdiv">
                    <div class="col-lg-12">
                        <h1>Exclusive Hot Deal Ends Soon!</h1>
                        <p>Who are in extremely love with eco friendly system.</p>
                    </div>
                    <div class="col-lg-12">
                        <div class="row clock-wrap">
                            <div class="col clockinner1 clockinner">
                                <h1 class="days">150</h1>
                                <span class="smalltext">Days</span>
                            </div>
                            <div class="col clockinner clockinner1">
                                <h1 class="hours">23</h1>
                                <span class="smalltext">Hours</span>
                            </div>
                            <div class="col clockinner clockinner1">
                                <h1 class="minutes">47</h1>
                                <span class="smalltext">Mins</span>
                            </div>
                            <div class="col clockinner clockinner1">
                                <h1 class="seconds">59</h1>
                                <span class="smalltext">Secs</span>
                            </div>
                        </div>
                    </div>
                </div>
                <a href="" class="primary-btn">Shop Now</a>
            </div>
            <div class="col-lg-6 no-padding exclusive-right">
                <div class="active-exclusive-product-slider">
                    <!-- single exclusive carousel -->
                    <div class="single-exclusive-slider">
                        <img class="img-fluid" src="{% static 'homepage/img/product/e-p1.png' %}" alt="">
                        <div class="product-details">
                            <div class="price">
                                <h6>$150.00</h6>
                                <h6 class="l-through">$210.00</h6>
                            </div>
                            <h4>addidas New Hammer sole
                                for Sports person</h4>
                            <div class="add-bag d-flex align-items-center justify-content-center">
                                <a class="add-btn" href=""><span class="ti-bag"></span></a>
                                <span class="add-text text-uppercase">Add to Bag</span>
                            </div>
                        </div>
                    </div>
                    <!-- single exclusive carousel -->
                    <div class="single-exclusive-slider">
                        <img class="img-fluid" src="{% static 'homepage/img/product/e-p1.png' %}" alt="">
                        <div class="product-details">
                            <div class="price">
                                <h6>$150.00</h6>
                                <h6 class="l-through">$210.00</h6>
                            </div>
                            <h4>addidas New Hammer sole
                                for Sports person</h4>
                            <div class="add-bag d-flex align-items-center justify-content-center">
                                <a class="add-btn" href=""><span class="ti-bag"></span></a>
                                <span class="add-text text-uppercase">Add to Bag</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/homepage/features.html
{% load staticfiles %}
<section class="features-area section_gap">
    <div class="container">
        <div class="row features-inner">
            <!-- single features -->
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-features">
                    <div class="f-icon">
                        <img src="{% static 'homepage/img/features/f-icon1.png' %}" alt="">
                    </div>
                    <h6>Free Delivery</h6>
                    <p>Free Shipping on all order</p>
                </div>
            </div>
            <!-- single features -->
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-features">
                    <div class="f-icon">
                        <img src="{% static 'homepage/img/features/f-icon2.png' %}" alt="">
                    </div>
                    <h6>Return Policy</h6>
                    <p>Free Shipping on all order</p>
                </div>
            </div>
            <!-- single features -->
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-features">
                    <div class="f-icon">
                        <img src="{% static 'homepage/img/features/f-icon3.png' %}" alt="">
                    </div>
                    <h6>24/7 Support</h6>
                    <p>Free Shipping on all order</p>
                </div>
            </div>
            <!-- single features -->
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-features">
                    <div class="f-icon">
                        <img src="{% static 'homepage/img/features/f-icon4.png' %}" alt="">
                    </div>
                    <h6>Secure Payment</h6>
                    <p>Free Shipping on all order</p>
                </div>
            </div>
        </div>
    </div>
</section>

templates/homepage/footer.html
{% load staticfiles %}

<footer class="footer-area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Us</h6>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
                        magna aliqua.
                    </p>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">

                        <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                         method="get" class="form-inline">

                            <div class="d-flex flex-row">

                                <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                 required="" type="email">


                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                </div>

                                <!-- <div class="col-lg-4 col-md-4">
                                            <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                                        </div>  -->
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram Feed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="{% static 'homepage/img/i2.jpg' %}" alt=""></li>
                        <li><img src="{% static 'homepage/img/i1.jpg' %}" alt=""></li>
                        <li><img src="{% static 'homepage/img/i3.jpg' %}" alt=""></li>
                        <li><img src="{% static 'homepage/img/i4.jpg' %}" alt=""></li>
                        <li><img src="{% static 'homepage/img/i5.jpg' %}" alt=""></li>
                        <li><img src="{% static 'homepage/img/i6.jpg' %}" alt=""></li>
                        <li><img src="{% static 'homepage/img/i7.jpg' %}" alt=""></li>
                        <li><img src="{% static 'homepage/img/i8.jpg' %}" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
            <p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>
</footer>

templates/homepage/header.html
{% load staticfiles %}
<header class="header_area sticky-header">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="{% url 'core:home' %}"><img src="{% static 'homepage/img/logo.png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="{% url 'core:home' %}">Home</a></li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{% url 'product:category' 'plimsoll-sneakers' %}">Shop Category</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% static 'homepage/single-product.html' %}">Product Details</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% static 'homepage/checkout.html' %}">Product Checkout</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% static 'homepage/cart.html' %}">Shopping Cart</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% static 'homepage/confirmation.html' %}">Confirmation</a></li>
                            </ul>
                        </li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">Blog</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{% static 'homepage/blog.html' %}">Blog</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% static 'homepage/single-blog.html' %}">Blog Details</a></li>
                            </ul>
                        </li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">Pages</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}">Login</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% static 'homepage/tracking.html' %}">Tracking</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% static 'homepage/elements.html' %}">Elements</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% static 'homepage/contact.html' %}">Contact</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item"><a href="#" class="cart"><span class="ti-bag"></span></a></li>
                        <li class="nav-item">
                            <button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="search_input" id="search_input_box">
        <div class="container">
            <form class="d-flex justify-content-between">
                <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                <button type="submit" class="btn"></button>
                <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
            </form>
        </div>
    </div>
</header>

templates/homepage/home-banner.html
{% load staticfiles %}
<section class="banner-area">
    <div class="container">
        <div class="row fullscreen align-items-center justify-content-start">
            <div class="col-lg-12">
                <div class="active-banner-slider owl-carousel">
                    <!-- single-slide -->
                    <div class="row single-slide align-items-center d-flex">
                        <div class="col-lg-5 col-md-6">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    <span class="add-text text-uppercase">Add to Bag</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="{% static 'homepage/img/banner/banner-img.png' %}" alt="">
                            </div>
                        </div>
                    </div>
                    <!-- single-slide -->
                    <div class="row single-slide">
                        <div class="col-lg-5">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    <span class="add-text text-uppercase">Add to Bag</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="{% static 'homepage/img/banner/banner-img.png/' %}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/homepage/home.html
{% extends "homepage/base.html" %}
{% load staticfiles %}

{% block title %}Trang chủ{% endblock %}

{% block sitecss %}
	<link rel="stylesheet" href="{% static 'homepage/css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/nouislider.min.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/ion.rangeSlider.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/ion.rangeSlider.skinFlat.css' %}" />
	<link rel="stylesheet" href="{% static 'homepage/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/main.css' %}">
{% endblock %}

{% block banner-area %}
	{% include 'homepage/home-banner.html' %}	
{% endblock banner-area %}

{% block features-area %}
	{% include 'homepage/features.html' %}	
{% endblock features-area %}

{% block category-area %}
	{% include 'homepage/category.html' %}	
{% endblock category-area %}

{% block product %}
	<section class="owl-carousel active-product-area section_gap">
		<!-- single product slide -->
		<div class="single-product-slider">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-6 text-center">
						<div class="section-title">
							<h1>Latest Products</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
								dolore
								magna aliqua.</p>
						</div>
					</div>
				</div>
				<div class="row">
					<!-- single product -->
					{% for Product in Products %}
						<div class="col-lg-3 col-md-6">
							<div class="single-product">
								<a href="{% url 'product:product-detail' Product.id %}"><img class="img-fluid" src="{{Product.image.url}}" width="262px" height="280px" alt=""></a>
								<div class="product-details">
									<h6>{{Product.title}}</h6>
									<br>
									<div class="price">
										<h6>${{Product.price}}</h6>
										<h6 class="l-through">{{Product.price}}</h6>
									</div>
									<div class="prd-bottom">

										<a href="{% static 'homepage/cart.html' %}" class="social-info">
											<span class="ti-bag"></span>
											<p class="hover-text">add to bag</p>
										</a>
										<a href="{% static 'homepage/login.html' %}" class="social-info">
											<span class="lnr lnr-heart"></span>
											<p class="hover-text">Wishlist</p>
										</a>
										<a href="" class="social-info">
											<span class="lnr lnr-sync"></span>
											<p class="hover-text">compare</p>
										</a>
										<a href="{% url 'product:product-detail' Product.id %}" class="social-info">
											<span class="lnr lnr-move"></span>
											<p class="hover-text">view more</p>
										</a>
									</div>
								</div>
							</div>
						</div>					
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- single product slide -->
		<div class="single-product-slider">
			{% comment %} <div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-6 text-center">
						<div class="section-title">
							<h1>Coming Products</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
								dolore
								magna aliqua.</p>
						</div>
					</div>
				</div>
				<div class="row">
					{% for Product in Products %}
						<div class="col-lg-3 col-md-6">
							<div class="single-product">
								<img class="img-fluid" src="{{Product.image.url}}" width="262px" height="280px" alt="">
								<div class="product-details">
									<h6>{{Product.title}}</h6>
									<div class="price">
										<h6>${{Product.price}}</h6>
										<h6 class="l-through">{{Product.price}}</h6>
									</div>
									<div class="prd-bottom">

										<a href="" class="social-info">
											<span class="ti-bag"></span>
											<p class="hover-text">add to bag</p>
										</a>
										<a href="" class="social-info">
											<span class="lnr lnr-heart"></span>
											<p class="hover-text">Wishlist</p>
										</a>
										<a href="" class="social-info">
											<span class="lnr lnr-sync"></span>
											<p class="hover-text">compare</p>
										</a>
										<a href="" class="social-info">
											<span class="lnr lnr-move"></span>
											<p class="hover-text">view more</p>
										</a>
									</div>
								</div>
							</div>
						</div>					
					{% endfor %}
					
				</div>
			</div> {% endcomment %}
		</div>
	</section> 
{% endblock %}

{% block exclusive-deal %}
	{% include 'homepage/exclusive-deal.html' %}
{% endblock exclusive-deal %}

{% block brand-section_gap %}
	{% include 'homepage/brand-section_gap.html' %}
{% endblock brand-section_gap %}

{% block related-product %}	
	{% include 'homepage/related-product.html' %}
{% endblock related-product %}

{% block sitejs %}
	<script src="{% static 'homepage/js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	crossorigin="anonymous"></script>
	<script src="{% static 'homepage/js/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.sticky.js' %}"></script>
	<script src="{% static 'homepage/js/nouislider.min.js' %}"></script>
	<script src="{% static 'homepage/js/countdown.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'homepage/js/owl.carousel.min.js' %}"></script>
	<!--gmaps Js-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
	<script src="{% static 'homepage/js/gmaps.min.js' %}"></script>
	<script src="{% static 'homepage/js/main.js' %}"></script>
{% endblock %}