ShoeStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView

app_name = 'core'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
]

user/urls.py
from django.urls import path
from .views import RegisterView, LoginView

app_name = 'user'

urlpatterns = [
    path('register/', RegisterView, name='register'),
    path('login/', LoginView, name='login'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
# Create your models here.


class CustomerUserManager(UserManager):
    def create_superuser(self, username, email, first_name, last_name, phone_number, country, province, district, address, postcode, password=None):
        user_obj = self.model(
            username=username,
            email=email,
            first_name=first_name,
            last_name=last_name,
            is_staff=True,
            is_active=True,
            is_superuser=True,
            phone_number=phone_number,
            country=country,
            province=province,
            district=district,
            address=address,
            postcode=postcode,

        )
        user_obj.set_password(password)
        # user_obj.phone_number = phone_number
        # user_obj.country = country
        # user_obj.province = province
        # user_obj.district = district
        # user_obj.address = address
        # user_obj.postcode = postcode
        user_obj.save(using=self._db)
        return user_obj


class CustomerUser(AbstractUser):
    phone_number = models.CharField(max_length=15, default='')
    country = models.CharField(max_length=50, default='')
    province = models.CharField(max_length=50, default='')
    district = models.CharField(max_length=50, default='')
    address = models.CharField(max_length=255, default='')
    postcode = models.CharField(max_length=10, default='')

    objects = CustomerUserManager()

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    # active = models.BooleanField(default=True)
    # staff = models.BooleanField(default=False)
    # admin = models.BooleanField(default=False)

    # @property
    # def is_staff(self):
    #     return self.staff

    # @property
    # def is_admin(self):
    #     return self.admin

    # @property
    # def is_active(self):
    #     return self.active

user/views.py
from django.shortcuts import render, redirect
from django.views import View
from .form import LoginForm, RegisterForm
from django.contrib.auth import authenticate, login, get_user_model
from .models import CustomerUser
# Create your views here.

User = get_user_model()


def RegisterView(request):
    form = RegisterForm(request.POST or None)
    context = {"form": form}
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        country = form.cleaned_data.get("country")
        phone_number = form.cleaned_data.get("phone_number")
        province = form.cleaned_data.get("province")
        distric = form.cleaned_data.get("distric")
        address = form.cleaned_data.get("address")
        postcode = form.cleaned_data.get("postcode")
        new_user = User.objects.create_superuser(username, email, first_name, last_name, phone_number, country, province, distric, address, postcode, password)
        if new_user is not None:
            return redirect("/user/login")
    return render(request, 'user/register.html', context)


def LoginView(request):
    form = LoginForm(request.POST or None)
    context = {"form": form}
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/home")
    return render(request, 'user/login.html', context)

templates/user/login.html
{% extends "homepage/base.html" %}
{% load staticfiles %}

{% block sitecss %}
	<link rel="stylesheet" href="{% static 'homepage/css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/nouislider.min.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/main.css' %}">
{% endblock sitecss %}

{% block banner-area %}
    {% include "product/banner-organic-breadcrumb.html" %}
{% endblock banner-area %}

{% block product-area %}
    <section class="login_box_area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="login_box_img">
                        <img class="img-fluid" src="{% static 'homepage/img/login.jpg' %}" alt="">
                        <div class="hover">
                            <h4>New to our website?</h4>
                            <p>There are advances being made in science and technology everyday, and a good example of this is the</p>
                            <a class="primary-btn" href="{% url 'user:register' %}">Create an Account</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="login_form_inner">
                        <h3>Log in to enter</h3>
                        <form class="row login_form" action="" method="post" id="loginForm" novalidate="novalidate">
                            {% csrf_token %}
                            <div class="col-md-12 form-group">
                                {% if form.errors %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endif %}    
                            </div>                        
                            <div class="col-md-12 form-group">
                                    {{form.username}}
                                    {{form.password}}
                                <div class="creat_account">
                                    <input type="checkbox" id="f-option2" name="selector">
                                    <label for="f-option2">Keep me logged in</label>
                                </div>
                                <button type="submit" value="submit" class="primary-btn">Log In</button>
                                <a href="#">Forgot Password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock product-area %}

{% block sitejs %}
	<script src="{% static 'homepage/js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="{% static 'homepage/js/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.sticky.js' %}"></script>
	<script src="{% static 'homepage/js/nouislider.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'homepage/js/owl.carousel.min.js' %}"></script>
	<!--gmaps Js-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
	<script src="{% static 'homepage/js/gmaps.min.js' %}"></script>
	<script src="{% static 'homepage/js/main.js' %}"></script>
{% endblock sitejs %}

templates/user/register.html
{% extends "homepage/base.html" %}
{% load staticfiles %}

{% block sitecss %}
	<link rel="stylesheet" href="{% static 'homepage/css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/nouislider.min.css' %}">
	<link rel="stylesheet" href="{% static 'homepage/css/main.css' %}">
{% endblock sitecss %}

{% block banner-area %}
    {% include "product/banner-organic-breadcrumb.html" %}
{% endblock banner-area %}

{% block product-area %}
    <section class="checkout_area section_gap">
        <div class="container">
            <div class="register">
                <div class="row">
                    <div class="col-lg-8" style="margin: 0 auto">
                        <center><h2>REGISTER</h2></center>
                        <br>
                        <form class="row contact_form" action="" method="post" id="registerForm" novalidate="novalidate">
                            {% csrf_token %}
                            <div class="col-md-12 form-group p_star">
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}    
                            </div>                        
                            <div class="col-md-6 form-group p_star">
                                {{form.username}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                {{form.email}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                {{form.password}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                {{form.confirm_password}}
                            </div>
                            <br>
                            <div class="col-md-12 form-group">        
                                <center><h4>OTHER INFORMATION</h4></center>
                            </div>
                            <br>
                            <div class="col-md-6 form-group p_star">
                                {{form.first_name}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                {{form.last_name}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                {{form.country}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                {{form.phone_number}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                {{form.province}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                {{form.distric}}
                            </div>
                            <div class="col-md-12 form-group p_star">
                                {{form.address}}
                            </div>
                            <div class="col-md-12 form-group">
                                {{form.postcode}}
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <center><button type="submit" value="submit" class="primary-btn">Register</button></center>                           
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock product-area %}
{% block sitejs %}
	<script src="{% static 'homepage/js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="{% static 'homepage/js/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.sticky.js' %}"></script>
	<script src="{% static 'homepage/js/nouislider.min.js' %}"></script>
	<script src="{% static 'homepage/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'homepage/js/owl.carousel.min.js' %}"></script>
	<!--gmaps Js-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
	<script src="{% static 'homepage/js/gmaps.min.js' %}"></script>
	<script src="{% static 'homepage/js/main.js' %}"></script>
{% endblock sitejs %}